### PR TITLE
JBPM-6803: Migrate server template selector to breadcrumb area.

### PR DESCRIPTION
**Pull request by nmirasch**

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai @bsremac could you take a look? thanks!

**Comment by cristianonicolai** [comment]
@nmirasch overall looks good to me. I've pushed some cosmetic changes in https://github.com/nmirasch/jbpm-console-ng/pull/2, restyling the selector to match the designs.

**Comment by nmirasch** [comment]
@cristianonicolai much better, thanks!

**Comment by bsremac** [comment]
+1

**Review by cristianonicolai — APPROVED** [review]

**Comment by cristianonicolai** [comment]
@nmirasch thanks!

**Pull request merged**
