### PR TITLE
JBPM-6886 : Update Dashboards layout

### PR DESCRIPTION
**Pull request by nmirasch**

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai @bsremac could you take a look? thanks!

**Comment by cristianonicolai** [comment]
@nmirasch overall looks good, I'm just wondering that we should use a btn-link style (same as the refresh) for the switch. Also, would be nice to have a title in the button, something like_View table_ and _View dashboard_.

**Comment by nmirasch** [comment]
@cristianonicolai  I have added it as a link, let's see if it fits now. Let me know what do you think, Thanks!

**Comment by cristianonicolai** [comment]
@nmirasch looks great! Just a minor tweak, not a blocker, to make these icons blue, same as the refresh one.

**Review by cristianonicolai — APPROVED** [review]

**Pull request merged**
