### PR TITLE
JBPM-7007 - Use table header height as offset to calculate total height

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Depends on https://github.com/kiegroup/appformer/pull/237

**Comment by cristianonicolai** [comment]
@nmirasch @bsremac please take a look.

**Comment by bsremac** [comment]
@cristianonicolai I'm again having problems compiling.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project jbpm-wb-common-client: Compilation failure: Compilation failure:
[ERROR] /home/bsremac/Devel/github.com/cristianonicolai/jbpm-wb/jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/menu/RefreshMenuBuilder.java:[46,41] cannot find symbol
[ERROR] symbol:   method getElement()
[ERROR] location: variable menuRefreshButton of type org.uberfire.client.views.pfly.widgets.Button
[ERROR] /home/bsremac/Devel/github.com/cristianonicolai/jbpm-wb/jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/menu/RefreshMenuBuilder.java:[66,26] cannot find symbol
[ERROR] symbol:   method getElement()
[ERROR] location: variable menuRefreshButton of type org.uberfire.client.views.pfly.widgets.Button
[ERROR] /home/bsremac/Devel/github.com/cristianonicolai/jbpm-wb/jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/util/ConditionalKebabActionCell.java:[87,43] cannot find symbol
[ERROR] symbol:   variable DropPosition
[ERROR] location: class org.uberfire.client.views.pfly.widgets.KebabMenu
[ERROR] /home/bsremac/Devel/github.com/cristianonicolai/jbpm-wb/jbpm-wb-common/jbpm-wb-common-client/src/main/java/org/jbpm/workbench/common/client/util/ConditionalKebabActionCell.java:[98,21] cannot find symbol
[ERROR] symbol:   method addSeparator()
[ERROR] location: variable menu of type org.uberfire.client.views.pfly.widgets.KebabMenu
```

**Comment by cristianonicolai** [comment]
@bsremac ok, I rebased the PR on appformer, should be good now.

**Review by bsremac — APPROVED** [review]

**Pull request closed without merging**
