### PR TITLE
Move detail screens to full screen

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch @bsremac I think we should move to full details page sooner, that way we can present and review its content with the UX team.

**Comment by bsremac** [comment]
@cristianonicolai Yes, it makes sense. 
If we know that the new table will be ready for GA, there's no reason to postpone this.

**Review by bsremac — APPROVED** [review]

**Review by nmirasch — APPROVED** [review]

**Comment by bsremac** [comment]
@cristianonicolai @nmirasch One thing which now stands out is forcing the full screen process instance details after starting a new process instance in _Process Definitions_ view.
While the details of the newly started process instance were in the side panel, they could be ignored and the interaction with the process definitions list could be seamlessly continued. Whatever requirement was behind this old approach, seems to be now overridden with the master details idea.

**Comment by bsremac** [comment]
@cristianonicolai @nmirasch There is one issue when interacting with process instance master detail in _Process Instances_ view.
Basically you navigate to Process Instances (advanced filter is set to show only _Active_ ones at that moment) and you click on one of the process instances in the list.
The full screen master detail opens up and so far so good.
But then when you close the view, no matter in which way (go back via breadcrumbs or using the close button), the process instances list is empty.
In order to get the active process instances back, which were listed before navigating to details view, you have to use the _Refresh_ button.

Actually, it seems that this behavior is not exclusive for Process Instances details view, but for all details views.

**Pull request merged**
