### PR TITLE
JBPM-6867 - Layout updates to manage result list

### PR DESCRIPTION
**Pull request by cristianonicolai**
- Fix scrolling
- Remove table rows stripes
- Add grey background to table header

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch @bsremac please have a look.

**Review by nmirasch — APPROVED** [review]

**Comment by bsremac** [comment]
What was agreed in the end regarding the line between the table header and _Search Results_? With line or without?
screenshot from 2018-02-28 22-00-20

When I enable all the columns, i.e. in Process Instances perspective, the content of the most right column (Chrome) or the most left column (in Firefox) gets trimmed.
FF:
screenshot from 2018-02-28 22-00-33

Chrome:
screenshot from 2018-02-28 22-00-51

I guess in case of Chrome the problem will go away when the actions are switched from buttons to kebab, but in Firefox those check-boxes don't look nice.

**Comment by cristianonicolai** [comment]
@bsremac my understanding was to keep the border because we added the background color there.
Correct, once we add the kebab the action column will be fixed.
Will check the checkbox issue.

**Comment by cristianonicolai** [comment]
@bsremac done, fixed checkbox issue.

**Review by bsremac — APPROVED** [review]

**Pull request merged**
