### PR TITLE
Review toolbar primary action buttons

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@nmirasch @bsremac, please take a look.

**Comment by bsremac** [comment]
@cristianonicolai So when it comes to Process Instance Details view, we won't set the primary action there? It will be just a kebab menu to select from, is it?
screenshot from 2018-02-17 19-40-23

**Comment by cristianonicolai** [comment]
I believe we will end up with two default buttons in here (signal and abort) once the process model option is removed based on the last conversations we had with the UX team. At least that was the intention. If we think that it isn't an issue to leave only the process model option in the kebab I can get that adjusted in here.
@nmirasch  @bsremac wdyt?

**Comment by bsremac** [comment]
@cristianonicolai I would go straight to _Signal/Abort_ buttons and leave only _Process Model_ in the kebab which will go away anyway. The reason I think this is because the interim kebab solution will never see the light of the day and having the "closest to the final solution" will make my Selenium tests re-factoring easier as I would have more pieces in place sooner than later.

**Comment by cristianonicolai** [comment]
@bsremac +1, I updated the PR to reflect that.

**Comment by bsremac** [comment]
@cristianonicolai Thanks!

**Review by bsremac — APPROVED** [review]

**Pull request merged**
